### ISSUE TITLE
Better handling for default volume

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#110]
The default volume is not properly selected, we should either rely on Cinder to select the default volume if none is specified or fail early.

**Comment by okozachenko1203** [comment]
@mnaser could you share more context here?
Default volume means `boot_volume_type` or `etcd_volume_type`?

**Comment by mnaser** [comment]
> @mnaser could you share more context here? Default volume means `boot_volume_type` or `etcd_volume_type`?

Correct, we're using this function:

https://github.com/vexxhost/magnum/blob/cf2f0659ff255eae56040e0ecc64c1138cde7fe0/magnum/common/cinder.py#L30-L32

Essentially, it should not be `_get_random_volume_type` but maybe instead we should detect what is the default volume type in Cinder and use that?
