### ISSUE TITLE
Extra arguments for kube-apiserver static pod

### ISSUE THREAD

**Issue by jan-di** [vexxhost/magnum-cluster-api#115]
Hi guys, great work so far!

We are currently have the need to specify additional extra command line args at the kube-apiserver static pod, that resides in `/etc/kubernetes/manifests/kube-apiserver.yaml`. This should be doable by insert variable arguments in the kubeadm config (https://github.com/vexxhost/magnum-cluster-api/blob/61f6855315b23fd3134daf8730fddb50c0b63b54/magnum_cluster_api/resources.py#LL424C1-L424C32)

My proposal would be to reimplement magnum/heat's `kubeapi_options` to allow to specify additional args. Like "--arg1=value1 --arg2=value2". 

Do you agree?

**Comment by fnpanic** [comment]
I would also agree here with @mnaser. We should discuss the usecases and then make them default if it is for example the cipher suites.

**Comment by jan-di** [comment]
Our current use case is using AzureAD as a OIDC provider for the kube-apiserver, to be able to login via AzureAD/[Kubelogin](https://github.com/Azure/kubelogin)

This means we need to provide the oidc arguments to apiserver. This includes some tenant/application specific arguments. 

```yaml
# kubeadm config

    - "--oidc-client-id=123e4567-e89b-12d3-a456-426614174000"
    - "--oidc-issuer-url=https://sts.windows.net/123e4567-e89b-12d3-a456-426614174000/"
    - "--oidc-username-claim=upn"
    - "--oidc-username-prefix=aad:"
    - "--oidc-groups-claim=groups"
    - "--oidc-groups-prefix=aad:"
```

Apart from that, I would still like to have the option to pass arbitrary arguments, to prevent needing a code change in magnum for small things.

**Comment by fnpanic** [comment]
@jan-di From my point of view this is a valid usecase in our enviroment and makes sense as a general option for all users.  The problem i see here is that it can fail in many ways which are not reflected correctly in magnum which makes this not so useful.

**Comment by mnaser** [comment]
Closing in favour of https://github.com/vexxhost/magnum-cluster-api/issues/119
