### ISSUE TITLE
Dynamically add all StorageClass

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#12]
An OpenStack cloud can have many volume types.  Instead of having a disconnect between the Kubernetes cluster and the OpenStack cloud, we should automatically poll for all the volume types and create `StorageClass` for them.

In the same time, we will also make the default `StorageClass` the one which is default in the cloud, that will make things nice and simple for the user.

**Comment by okozachenko1203** [comment]
I am on it
