### ISSUE TITLE
Custom NTP values from DHCP or DNS

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/magnum-cluster-api#163]
With the acceptance of PR https://github.com/kubernetes-sigs/image-builder/pull/1225 it is possible for the Ubuntu k8s images to to get custom NTP values from DHCP option 42 and/or DNS _ntp._udp DNS SRV records.

Would be great if we can include this bug fix/feature into the qemu images.

**Comment by mnaser** [comment]
The new images that are built already include these fixes.
