### ISSUE TITLE
Magnum Cluster Template creation failure

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/magnum-cluster-api#168]
When attempting to create a Magnum cluster template based on an Ubuntu 22.04 image we are getting an error that indicates that Ubuntu 22.04 isn't supported. I'm sure its a misconfiguration on our end, but I haven't discovered the root cause. I can say that I can upload the image just fine to Glance, and I can spin up VM's based on that image, but the cluster template commands fail:

```sh
❯ openstack coe cluster template create \
  --image $(openstack image show ubuntu-2204-kube-v1.27.3 -c id -f value) \
  --external-network public \
  --dns-nameserver 1.1.1.1 \
  --master-lb-enabled \
  --master-flavor m1.medium \
  --flavor m1.medium \
  --network-driver calico \
  --docker-storage-driver overlay2 \
  --coe kubernetes \
  --label kube_tag=v1.27.3 \
  --label boot_volume_size=40 \
  --label boot_volume_type=rbd1 \
  --label master_lb_floating_ip_enabled=false \
  --label audit_log_enabled=true \
  default-k8s-v1.27.3-ubuntu-2204-calico;
Cluster type (vm, ubuntu-jammy, kubernetes) not supported (HTTP 400) (Request-ID: req-bc0d3bc8-4529-4d15-8885-525b5fa5d93b)
```

The magnum-api logs just show:

```log
/var/lib/openstack/lib/python3.10/site-packages/magnum/drivers/common/driver.py:38: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  yield entry_point, entry_point.load(require=False)
2023-07-18 18:43:00.235 1 INFO werkzeug [None req-f47c13c5-fe27-4e37-8cf9-01ed5f83520e edc0f55dab5d4a10ab0b237d690158aa 978a5ab908fc477f9fa42c348e2c54d2 default - - -] 172.18.32.245 - - [18/Jul/2023 18:43:00] "POST /v1/clustertemplates HTTP/1.1" 400 -
```

I didn't see anything in the magnum-conductor or magnum cluster proxy logs but can certainly provide them if you want.

**Comment by mnaser** [comment]
hi @runlevel-six !

since CAPI doesn't really care/mind if you're using ubuntu jammy or focal, we've moved towards using `ubuntu` only for os_distro, so if you swap out to that you should be all good to go. :)

thanks!

**Comment by runlevel-six** [comment]
That resolved it, @mnaser. Thank you!
