### ISSUE TITLE
stuck in DELETE_IN_PROGRESS

### ISSUE THREAD

**Issue by migmeneses** [vexxhost/magnum-cluster-api#188]
We created two test clusters and they are stuck in DELETE_IN_PROGRESS

Looking at the events and logs we found:
`openstack coe cluster show <id or name>`
```
CAPI Cluster status: . CAPI OpenstackCluster status reason: Faileddeletesecuritygroup: Failed to delete security group k8s-cluster-magnum-system
-kube-33oj6-secgroup-controlplane with id c51c6577-c5ea-4890-ad3c-3e5892818661: Expected HTTP response code [202 204] when accessing [DELETE https://network.openstack.vi
stex.local/v2.0/security-groups/c51c6577-c5ea-4890-ad3c-3e5892818661], but got 409 instead
```
The security group still exist. 

Before ( around 3 hrs before ) was showing, that it could not delete X loadbalancer, I checked and it no longer exist

Let us know if you need further logs, to clarify this issue.

Regards

**Comment by okozachenko1203** [comment]
This 409 error means SG is consumed still by any port or VM. Could you check which resource(s) is(are) consuming this SG still and why those resources not deleted?

**Comment by migmeneses** [comment]
There are several ports with the same stack_id ( of the cluster stuck on DELETE_IN_PROGRESS )

**Comment by migmeneses** [comment]
there are 24x ports related to the cluster in DELETE_IN_PROGRESS 
and 9 of them are related to the security group listed above

**Comment by okozachenko1203** [comment]
> there are 24x ports related to the cluster in DELETE_IN_PROGRESS and 9 of them are related to the security group listed above

I suggest checking neutron log why those ports are delete in progress.

**Comment by okozachenko1203** [comment]
fyi, also we have another open issue https://github.com/vexxhost/magnum-cluster-api/issues/63 related to upstream CAPI https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1404
Please check the neutron log and confirm if this is the same case. Then lets close this issue to avoid duplication

**Comment by migmeneses** [comment]
> fyi, also we have another open issue #63 related to upstream CAPI [kubernetes-sigs/cluster-api-provider-openstack#1404](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1404) Please check the neutron log and confirm if this is the same case. Then lets close this issue to avoid duplication

Hi there,
Well so far the workaround presented on #63 works for this case

**Comment by migmeneses** [comment]
Duplicated: https://github.com/vexxhost/magnum-cluster-api/issues/63
