### ISSUE TITLE
Support for Image Name in Cluster Templates

### ISSUE THREAD

**Issue by migmeneses** [vexxhost/magnum-cluster-api#193]
## Bug Description:

The current  Magnum CAPI does not support using image names in cluster templates. This limitation results in clusters getting stuck in a "DELETE_IN_PROGRESS" state when the image_id in the template is specified as an image name rather than a UUID.

## Root Cause:

Magnum CAPI currently expects the image_id in cluster templates to be a UUID, and this presents a limitation.

**Comment by okozachenko1203** [comment]
I think it is better to add a pre-check for image existence and image id format and return a proper error if image name is provided because image names are not unique.

**Comment by mnaser** [comment]
@okozachenko1203 unfortunately the magnum api seems to accept both, so we should accept both, if it's id format, success.  if it's a name, we pull the images, if it matches a SINGLE image only, then we pass that into CAPI.
