### ISSUE TITLE
Regression with Cinder volume type

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#200]
https://github.com/vexxhost/magnum-cluster-api/commit/fceabedb2e8913b8bff858073f6eb532c4d93dc3#diff-43c5da84e3410f51531d7b4f6bdfe0b0f83fe9a19018cf1dde7ee2ef352bb019R232

With this change, we've changed the volume type to be `cinder-VOLUME_TYPE` instead :(

We should revert that and also add a unit test to track this.

**Comment by okozachenko1203** [comment]
> [fceabed#diff-43c5da84e3410f51531d7b4f6bdfe0b0f83fe9a19018cf1dde7ee2ef352bb019R232](https://github.com/vexxhost/magnum-cluster-api/commit/fceabedb2e8913b8bff858073f6eb532c4d93dc3#diff-43c5da84e3410f51531d7b4f6bdfe0b0f83fe9a19018cf1dde7ee2ef352bb019R232)
> 
> With this change, we've changed the volume type to be `cinder-VOLUME_TYPE` instead :(
> 
> We should revert that and also add a unit test to track this.

@mnaser That is intended change to avoid SC name collision when we have the share type and volume type with the same name.
What is the problem with that new naming here?

**Comment by mnaser** [comment]
@okozachenko1203 @jan-di if we're "breaking" here, wouldn't it be nicer than perhaps we changed the prefix to something like "block-<TYPE>" so it would be something like "block-nvme" or so, and then maybe "share-nfs-<TYPE>" for nfs type shares that use NFS?

It would feel a bit more descriptive?

**Comment by okozachenko1203** [comment]
> @okozachenko1203 @jan-di if we're "breaking" here, wouldn't it be nicer than perhaps we changed the prefix to something like "block-" so it would be something like "block-nvme" or so, and then maybe "share-nfs-" for nfs type shares that use NFS?
> 
> It would feel a bit more descriptive?

I think `block-` is ok. But for `share-nfs-`, i think we cannot know the share backend type just from the share name and nfs is just one amongst available type. So I think we cannot strict it as nfs, rather just `share-`.
