### ISSUE TITLE
Support GPU enabled cluster

### ISSUE THREAD

**Issue by josedev-union** [vexxhost/magnum-cluster-api#230]
We deploy k8s clusters using ansible playbook on Openstack.
To commission gpu enabled nodes in the cluster, we install gpu driver and nvidia-container runtime on nodes.
Can we make this done by using this driver also?
If that is not supported by upstream cluster-api, i think we can try [cluster-api-addon-provider-helm](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm) and install nvidia-operator on gpu nodes as helm chart.

**Comment by mnaser** [comment]
@josedev-union hi! 👋 

I believe there is an operator that can sort all of this out correct?  Would all that be necessary be using the addon provider to install the NVIDIA operator via Helm and we'll be good to go?

https://github.com/NVIDIA/gpu-operator

@mdbooth: curious if this makes sense to go into CAPO or not really?

**Comment by josedev-union** [comment]
@mnaser Apologies for the delayed response.

I have successfully installed it using gpu-operator, and the cluster deployment scripts do not need any modifications. Therefore, I will close this issue in favor of gpu-operator.
Thanks!

**Comment by mnaser** [comment]
@josedev-union awesome!  do you have some docs you can share?
