### ISSUE TITLE
Enable `availability_zone` label for clusters

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#257]
https://docs.openstack.org/magnum/latest/user/index.html#high-availability

We need to make sure that all the components such such as CSI, etc.

**Comment by ngyenhuukhoi** [comment]
Thank you.
That what I am currious.

**Comment by satishdotpatel** [comment]
+1  I am looking for this solution desperately. Its kind of blocker us for multi-master nodes controlplane.
