### ISSUE TITLE
Need proxy label

### ISSUE THREAD

**Issue by nguyenhuukhoi** [vexxhost/magnum-cluster-api#258]
Hello guys.

Could we add proxy labels for this driver?
It will be a nice feature.

I am trying understand our code.

Thank you.

**Comment by ngyenhuukhoi** [comment]
This can achieve by add openstack user-config when we launch instances. Could you give some keywords to code this function. I cannot  find location which I inspect this option.

**Comment by mnaser** [comment]
@ngyenhuukhoi do you mean you want the VMs to be created would have an HTTP proxy configured on them? (Curious if @jrosser is interested by it)

**Comment by ngyenhuukhoi** [comment]
yes, it looks like we cannot deploy magnum cluster under proxy. I have to add http proxy for containerd to images first.

**Comment by jrosser** [comment]
I did a bunch of work to the heat driver in the past to support deployment of workload clusters behind a proxy server.

That said, I've not looked at this at all for magnum-cluster-api and whilst I can use a local registry to prove that the workload cluster deployment is successful behind a proxy this fairly obviously leaves users with a functional but unusable cluster.

**Comment by ngyenhuukhoi** [comment]
Hello. 
Does insecure registry still can use with this driver?

**Comment by jrosser** [comment]
@mnaser I think that this issue needs re-opening.

A systemd drop-in for containerd which sets http/https_proxy environment, potentially also no_proxy for anything specified in `container_infra_prefix` will likely get things to the point where a workload cluster deployment will succeed behind an https proxy.

With certainty, the most wrong thing to do would be set proxy environment vars in `/etc/environment`, as this breaks absolutely everything about the cluster networking.

**Comment by nguyenhuukhoi** [comment]
Hello. Any updates on this.

**Comment by mnaser** [comment]
@nguyenhuukhoi this has been fixed by #281 thanks to @andrewbonney ! :)

**Comment by nguyenhuukhoi** [comment]
Thank you very much.
