### ISSUE TITLE
Endpoint configuration is incomplete

### ISSUE THREAD

**Issue by jrosser** [vexxhost/magnum-cluster-api#271]
I'm not fully understanding the distinction between `cloudControllerManagerConfig` and the `<cluster>-cloud-config`, however it is certainly true that adjusting cloudControllerManagerConfig in https://github.com/vexxhost/magnum-cluster-api/commit/8a5ffac1e0ed3f1a7166dfd15a62b74f6a140963 causes the public endpoint to be written irrespective of any config put into `magnum.conf/[capi_client]`.

Possibly`cloudControllerManagerConfig` should respect `[capi_client]` and also support the `os-endpoint-type` field? What is confusing is that capo is contacting our internal keystone endpoint (evidently ignoring what is in `cloudControllerManagerConfig`) but at that point it retrieves the external URL for neutron from the service catalog and that is not contactable.

Ambiguity here is really around knowing "this data is for the use of CAPO whilst it provisions resources" vs. "this data is to be inserted into the workload clusters"

Will add more to this bug if we discover it.

**Comment by mnaser** [comment]
@jrosser -- can we consider this closed at this point since I think we've ironed out most of the kinks around this?

**Comment by jrosser** [comment]
@mnaser yes i think this is pretty good now - we tested in a lab where the internal and public sides are do not NAT to each other so it has to be pretty spot on for that to work

**Comment by mnaser** [comment]
Thanks @jrosser
