### ISSUE TITLE
Magnum Cluster API Without Ocatavia

### ISSUE THREAD

**Issue by ngyenhuukhoi** [vexxhost/magnum-cluster-api#272]
Hello.
I see that CAPI support cluster without lb.  
 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/templates/cluster-template-without-lb.yaml

Do we have plan for this in future?

Because if we use octavia it will depend on network nodes, so single point of failure.

**Comment by mnaser** [comment]
I don't think there is a supported highly available method of creating clusters without Octavia. 

Do you mean to support single VM control plane with a floating IP?

**Comment by ngyenhuukhoi** [comment]
No, I mean multi control plan without LB. It will use provider network for node network. I see this template and just ask.

**Comment by ngyenhuukhoi** [comment]
Not support now.
