### ISSUE TITLE
User wont delete after a cluster was deleted

### ISSUE THREAD

**Issue by nguyenhuukhoi** [vexxhost/magnum-cluster-api#285]
Hello, Happy New Year.

I do not know if this is a function. I see that when we create a cluster then a keystone user will be created but when this cluster was deleted, user will not go away. 

It is better if we can delete the user when cluster will be deleted,

**Comment by satishdotpatel** [comment]
I have noticed similar issue and its annoying to see 100s of users in list.

**Comment by mnaser** [comment]
This seems to be an upstream issue inside Magnum:

https://review.opendev.org/c/openstack/magnum/+/905032

I would suggest keeping an eye open for that till it is merged and backported, we'll keep this issue open to track it.
