### ISSUE TITLE
Multi floating IPs were spawned if creating cluster without a router or a router without internal interfaces

### ISSUE THREAD

**Issue by nguyenhuukhoi** [vexxhost/magnum-cluster-api#289]
Hello.

"When I create a cluster without a router or a router without internal interfaces, it will automatically spawn floating IPs until there are no available IPs in this subnet."

My environment:
- Openstack Yoga
- Magnum Cluster API v0.13.2

**Comment by mnaser** [comment]
@ngyenhuukhoi this would be a cluster-api-provider-openstack bug, could you raise it there and link back to here?

**Comment by ngyenhuukhoi** [comment]
Hello.
I will do it.
Nguyen Huu Khoi

**Comment by ngyenhuukhoi** [comment]
Hello.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1827#issuecomment-1893644842

**Comment by mdbooth** [comment]
@mnaser Can you share the generated cluster config in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1827?

**Comment by mnaser** [comment]
Since I don't have that issue reproduced here, @ngyenhuukhoi can you please do the following, using the following as an example where the cluster ID is `cb371088-910c-49f7-93ed-15054d964648`.

```
kubectl -n magnum-system get cluster -l cluster-uuid=cb371088-910c-49f7-93ed-15054d964648 -oyaml
kubectl -n magnum-system get openstackcluster -l cluster.x-k8s.io/cluster-name=$(kubectl -n magnum-system get cluster -l cluster-uuid=cb371088-910c-49f7-93ed-15054d964648 -oname | cut -d'/' -f2) -oyaml
```

You can share that information in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1827

**Comment by nguyenhuukhoi** [comment]
fixed by:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1827#event-11514703479
