### ISSUE TITLE
Autoscaling

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#3]
Auto-scaling is a useful feature that used to exist inside Magnum, however, the Cluster API has [built-in autoscaling](https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/autoscaling.html).  We should enable it when `auto_scaling_enabled` is set to true.

I have not done significant research into this, so I will update this later once we have an idea how to get it all to work.

**Comment by mnaser** [comment]
we'll be needing to deal/use this for autoscale:

https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/autoscaling.html#autoscaler-running-in-management-cluster-using-service-account-credentials-with-separate-workload-cluster

**Comment by okozachenko1203** [comment]
on it
