### ISSUE TITLE
Proxy doesn't work reliably with OVN

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#301]
When using OVN as a network backend with the proxy component and running it on all the nodes, you end up in an issue where the endpoint slices can point to an instance that is non-functional, due to the fact that network namespaces in OVN (`ovnmeta`) are local and not across the network.

This means that if you're using Amphora's and your nodes are split across 10 hypervisors, then 1/10 will actually give a response and the rest will give an error, unfortunately.

What we need to do is actually make sure that the target IP is reachable before creating/adding the endpoint slice, moving the health check a stage above.

**Comment by mnaser** [comment]
I think the solution for this is going to be using the [`haproxyadmin`](https://github.com/unixsurfer/haproxyadmin) library which will be able to get the health status of all of the endpoints.  Based on that, if the endpoint is passing health checks, we can go ahead and add it to the endpoint slices, if it is not, it gets removed/not added.

This will make sure that _ONLY_ the `haproxy` instances that can reach the cluster will have endpoint slices.

**Comment by thywyn** [comment]
@mnaser Is there a corresponding image with the fix yet?

**Comment by mnaser** [comment]
@thywyn I've published a test image at `quay.io/vexxhost/magnum-cluster-api:48c2f912fd1f51feccaa7253efd713c7b6ce2128`
