### ISSUE TITLE
LB not work after reboot in kolla-ansible

### ISSUE THREAD

**Issue by mathgonzlez** [vexxhost/magnum-cluster-api#312]
Hi,

I'm encountering an issue with a deployment of an LB . The cluster configuration creates a load balancer (LB) with two interfaces that work great initially. However, after restarting or shutting down the LB VM, I can no longer reach my cluster. I've identified a couple of issues:

- After the LB creation, the VM only has one of the two interfaces inside the operating system.
- After a reboot, the second interface appears in the LB VM but without an IP address and in a DOWN state.

Due to these issues, I'm unable to use the Magnum cluster effectively. If the VM is restarted, I lose access to my cluster and can't reestablish it.

Thanks

**Comment by mnaser** [comment]
@mathgonzlez are you talking about rebooting the octavia amphora vm in this issue?

**Comment by mathgonzlez** [comment]
> @mathgonzlez are you talking about rebooting the octavia amphora vm in this issue?

Yes, exactly. after rebooting the octavia amphora this dont work anymore

**Comment by mathgonzalezz** [comment]
Hi @mnaser, any news about this? 

thanks!

**Comment by mathgonzlez** [comment]
Hi @mnaser, any news about this? thanks!

**Comment by mnaser** [comment]
@mathgonzlez I don't think this is actually related to the Cluster API driver, I think this might just be a problem with your environment/cloud because that seems to be an issue with the Octavia and Amphora if it's not coming back, nothing that the CAPI interact with directly.

**Comment by mathgonzlez** [comment]
> @mathgonzlez I don't think this is actually related to the Cluster API driver, I think this might just be a problem with your environment/cloud because that seems to be an issue with the Octavia and Amphora if it's not coming back, nothing that the CAPI interact with directly.

I see, youre right. Maybe is more related to octavia / image. i close the issue.

Thanks!
