### ISSUE TITLE
Cluster Templates Dropdown not populated

### ISSUE THREAD

**Issue by agillilandsp** [vexxhost/magnum-cluster-api#321]
In Horizon the magnum ui plugin is not populating the dropdown for upgrades.

Steps to reproduce.

- Create a cluster template at 1.27.3 and one at 1.27.4
- Create a cluster at 1.27.3.
- In the /project/clusters horizon view, Click on the right dropdown and select "Rolling Cluster Upgrade".
- You will note there is no dropdown.

The issue is in the logic associated with the `cluster.labels.kube_tag`. That is not populated. That field is used to determine the variable `activeTemplateVerison`.

See the attached image. You will see the variable in the upper right on a watch. The cluster data expanded below it. The kube_tag needed is actually in the labels_skipped.

![image](https://github.com/vexxhost/magnum-cluster-api/assets/104856366/a733d627-4ca2-4fa0-b22a-010f0683f028)

**Comment by mnaser** [comment]
FYI I think the issue here was the fact that there was missing `--merge-labels` so it did not have a `kube_tag` label.  Let me know if it fixes that issue.

**Comment by agillilandsp** [comment]
The merge labels flag added the kube_tag.
