### ISSUE TITLE
bug:ci pr body is mandatory now

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/magnum-cluster-api#342]
This line fails CIs instead of skipping for PRs having no body with this error 
```sh
Error in Start of Pipeline step.
Cannot invoke method contains() on null object
```
https://github.com/vexxhost/magnum-cluster-api/blob/2d3f3519d5e920d3a900bb6863c2643f42097370/Jenkinsfile#L4

**Comment by okozachenko1203** [comment]
for instance, https://github.com/vexxhost/magnum-cluster-api/pull/341/checks?check_run_id=22980579762

**Comment by mnaser** [comment]
Not valid anymore since we're moved to Zuul.
