### ISSUE TITLE
Cant get this to work on bobcat - multiple issues

### ISSUE THREAD

**Issue by flyersa** [vexxhost/magnum-cluster-api#406]
Hi all,

fresh Openstack Bobcat install with kolla. magnum-capi is already bundled in the magnum containers but in an old version, so i upgraded them to the latest (didnt help).

Nothing basically works right. I put the kubeconfig from the basecluster to all magnum containers which is fine. Basically followed this one linked from your docs page:

https://satishdotpatel.github.io/openstack-magnum-capi/

Issues:

- if kube_version metadata is not present on the images magnum will drop directly an error that the image doesnt have this value. So needs to be set 
- then on the try to spawn a cluster it will complain that it cant find helm release or CRDs from the stackhpc provider. So i applied them manually with:

`helm repo add capi-addons https://stackhpc.github.io/cluster-api-addon-provider

# Use the latest version from the main branch
helm upgrade \
  cluster-api-addon-provider \
  capi-addons/cluster-api-addon-provider \
  --install \
  --version ">=0.1.0-dev.0.main.0,<0.1.0-dev.0.main.9999999999"`

then on cluster creation the loadbalancer, controlplane and workers will spawn, but they are stuck. Nodes not getting in READY state because of no CNI available. All nodes have the "uninitalized" noSchedule taint.  Coredns will not even deploy (complains about this taints)

Removing the taints will at least get coredns deployed and the nodes put in READY state. But thats it. the clusters never get completed, no cni installed nothing and are stuck in create status. I even tried with different kubernetes cluster for the clusterctl one.

flatcar images do not work at all, they just go directly into a reboot loop having issues with the network. I tried v.1.27.4 and v.1.27.8 . The ubuntu22 ones at least do something.

Anyone has a idea? its stil pain that there is no real documentation or only outdated instructions. I also tried this on a different openstack setup (also on bobcat) to rule out something is wrong with my magnum setup. Same problems.

**Comment by flyersa** [comment]
I have no idea which one it is. according to the docs that you reference its yours that is also bundled.

`(magnum-api)[magnum@open-ctrl00 /]$ pip list | grep magnum
magnum                  17.0.3.dev1
magnum-capi-helm        1.0.0
magnum-cluster-api      0.21.0
python-magnumclient     4.2.0
`

pretty much looks like yours. As i said i followed the docs that you linked yourself on your docs page.

**Comment by mnaser** [comment]
That's pretty odd that it's asking for that.  We are actually running CI jobs against master so it should be working fine with the latest releases.

I can carve out 30 minutes of my time to try and figure out what the issue you're running into and looking into it together, feel free to ping me on Slack.

**Comment by flyersa** [comment]
Hi Mnaser,

well im sorry but it was most likely just our fault (outside stil the thing with the kube_version on the images). The drivers were disabled because the kubeconfig parameter was missing in the kolla configuration. doah ! :)   

Awesome work on this!
