### ISSUE TITLE
Add support for Flatcar Linux

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#42]
related:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1261
https://github.com/kubernetes-sigs/image-builder/issues/939

**Comment by lukasmrtvy** [comment]
ping, its doable now :)

**Comment by stefan-chivu** [comment]
Hi @all, I was wondering why the work for supporting Flatcar Linux has been halted. 

I would be interested to contribute and I'd like to know if the work done so far has any reason to be stopped or if it just happened to get to the back of the list of priorities.

**Comment by mnaser** [comment]
@stefan-chivu seems to have followed up!

https://kubernetes.slack.com/archives/C05Q8TDTK6Z/p1695293755953929

Hoping to see the PR soon :D

**Comment by mnaser** [comment]
closed by @stefan-chivu -- awesome work!
