### ISSUE TITLE
Keystone auth doesn't work with a custom CA

### ISSUE THREAD

**Issue by andrewbonney** [vexxhost/magnum-cluster-api#434]
It looks like there is a mismatch between the expectations of the keystoneauth 
Helm chart: https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/charts/k8s-keystone-auth/values.yaml#L20 and the way it is being set up: https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/resources.py#L416 (`ca_file` vs `ca_cert`).

Whilst the Helm chart may work if the file contents are passed in, this seems unnecessary as the nodes should already have this file in `/etc/kubernetes/cloud_ca.crt` and could just mount it as in https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/utils.py#L136.

**Comment by mnaser** [comment]
@okozachenko1203 when you're back, can you please have a look at this and evaluate which fix is the best?

Also, maybe we can try and figure out what kind of CI we can to avoid introducing some kind of regression.  I think long term, it would be better to start avoiding creating files on the host and rely on secrets that are mounted because those we can easily fix/change as opposed to editing files directly on disk that are host mounted.

**Comment by okozachenko1203** [comment]
@andrewbonney thanks for your report.
I'll just fix the key field of helm value. Helm chart renders a secret using ca_cert and mount it into daemonset already.
https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/charts/k8s-keystone-auth/templates/daemonset.yaml#L48-L51
https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/charts/k8s-keystone-auth/templates/daemonset.yaml#L63-L65
https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/charts/k8s-keystone-auth/templates/daemonset.yaml#L77-L80
https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/charts/k8s-keystone-auth/templates/secret-ca.yaml
On the other side, keeping ca crt file on node fs is a mcapi-specific implementation so it would be good to keep k8s-keystone-auth helm chart as standalone for loosely coupling.

**Comment by andrewbonney** [comment]
No problem. I've closed #435 and will leave #436 for review.
