### ISSUE TITLE
latest 2024.1 magnum image with db bugfix from yesterday doesnt work because of soft-affinity

### ISSUE THREAD

**Issue by flyersa** [vexxhost/magnum-cluster-api#463]
Good Morning,

i rolled the new magnum 2024.1 stable container yesterday which includes @mnaser bugfix for the sqlalchemy problem by using enginefacade. This for our build images also includes the latest vexxhost capi driver (0.24.0). But now while the DB issue is fixed it is not possible to start new clusters anymore with this error:

Invalid input for field/attribute 0. Value: soft-anti-affinity. 'soft-anti-affinity' is not one of ['anti-affinity', 'affinity']

I guess this is related to the last server-group change which was done on the driver?

**Comment by flyersa** [comment]
ok apparently

[nova_client]
api_version = 2.15

is required in magnum.conf now and the capi cluster needs to be on the latest version with the clusterctl stuff. should maybe mention that more in releases to not have people dug into the commits ;)

**Comment by noonedeadpunk** [comment]
I'd assume, that `2.15` is the minimum version required. In fact, I'd suggest using latest microversion for your openstack release:
https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#maximum-in-2023-1-antelope-and-2023-2-bobcat
