### ISSUE TITLE
Possible missing Apache2 License?

### ISSUE THREAD

**Issue by JohnGarbutt** [vexxhost/magnum-cluster-api#55]
It would be great to collaborate on this, and merge it with our helm approach.

Would you be willing to add an Apache2 Licence so we could do some of that please?

**Comment by mnaser** [comment]
@JohnGarbutt that should be ok, can you push in a PR with all the necessary changes for headers/etc?

**Comment by mnaser** [comment]
this is completed, the project is apache 2.0 licensed now.
