### ISSUE TITLE
Add documentation how to use with existing Openstack

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/magnum-cluster-api#56]

**Comment by okozachenko1203** [comment]
- install k8s cluster
- install cluster-api on the k8s cluster
- install magnum-cluster-api driver in magnum
- Copy kubeconfig file at the path `~/.kube/config` of magnum 
- Create coe cluster template

**Comment by ngyenhuukhoi** [comment]
Hello. 
*install k8s cluster
*install cluster-api on the k8s cluster

Could you explain why need these steps?

**Comment by okozachenko1203** [comment]
> Hello. *install k8s cluster *install cluster-api on the k8s cluster
> 
> Could you explain why need these steps?

@ngyenhuukhoi if i understood your question correctly, we need a management k8s cluster where cluster-api is running on because this driver depends on cluster-api.
You can follow this for cluster-api installation https://github.com/vexxhost/magnum-cluster-api/blob/main/hack/stack.sh#L80-L91

**Comment by ngyenhuukhoi** [comment]
Thank you for ur reply.
"install k8s cluster". what we do it after launching k8s via magnum or what. We need these step guide clearly with normal users. I am going to test this, only this step which I dont understand.

**Comment by okozachenko1203** [comment]
> Thank you for ur reply. "install k8s cluster". what we do it after launching k8s via magnum or what. We need these step guide clearly with normal users. I am going to test this, only this step which I dont understand.

This k8s cluster is not the cluster managed by Magnum.
This k8s cluster is just needed for cluster-api running. Cluster-api is the pre-requsite for this driver.

I drew an ugly arch picture. Hope it helps understanding.
This k8s cluster is a mgmt.cluster where cluster-api runs. Magnum and our driver will interact with cluster-api(running on the mgmt. cluster) to provision/de-provision workload clusters(coe clusters managed by magnum).

<img width="697" alt="magnum-capi-driver" src="https://user-images.githubusercontent.com/62775347/215805774-844c1902-6ea9-463e-99ca-35e59f48f6a7.png">

I suggest you take a look at the cluster-api docs and it will help you get things clearer https://cluster-api.sigs.k8s.io/introduction.html

**Comment by ngyenhuukhoi** [comment]
Ok, i got it with your picture. I will try to setup with your infonation.
Thank you very much.

**Comment by groundnuty** [comment]
Could you elaborate on

> * Copy kubeconfig file at the path `~/.kube/config` of magnum host
is it kubeconfig of management cluster so the magnum-cluster-api knows how to reach back to it? If so, then k8s cluster created with kind needs to have API port reachable over the network yep? 

I have the kolla setup, I ran `pip install magnum-cluster-api` inside magnum_api container and restarted:
```
/var/lib/kolla/venv/bin/python3 /var/lib/kolla/venv/bin/magnum-api --config-file /etc/magnum/magnum.conf
```
process. Is that enough? I don't want to build images yet.

Also, could you elaborate on how magnum-cluster-api 'hijacks' the normal magnum API, so that 'openstack coe cluster template create' command actually talks to magnum-cluster-api ? or maybe I understand the whole concept wrong?

**Comment by mnaser** [comment]
> @okozachenko1203 Could you elaborate on
> 
> > * Copy kubeconfig file at the path `~/.kube/config` of magnum host
> 
> is it kubeconfig of management cluster so the magnum-cluster-api knows how to reach back to it? If so, then k8s cluster created with kind needs to have API port reachable over the network yep?

This is correct!

> I have the kolla setup, I ran `pip install magnum-cluster-api` inside magnum_api container and restarted:
> 
> ```
> /var/lib/kolla/venv/bin/python3 /var/lib/kolla/venv/bin/magnum-api --config-file /etc/magnum/magnum.conf
> ```
> 
> process. Is that enough? I don't want to build images yet.

That should indeed be enough

> Also, could you elaborate on how magnum-cluster-api 'hijacks' the normal magnum API, so that `openstack coe cluster template create` command actually talks to magnum-cluster-api ? or maybe I understand the whole concept wrong?

We register a driver inside Magnum so that when `os_distro` is `ubuntu-focal`, then the driver is used:

https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/driver.py#L280-L285

**Comment by ngyenhuukhoi** [comment]
Can we change it from to Copy kubeconfig file at the path ~/.kube/config of magnum host Copy kubeconfig file at the path ~/.kube/config of k8s capi cluster to make it clear,

**Comment by ngyenhuukhoi** [comment]
Copy kubeconfig file at the path ~/.kube/config of magnum host
Could you help me understand this step.
ty much.

**Comment by mnaser** [comment]
FYI, we have created #151 and #152 -- we'll try and add support to those.

We've had a lot of interesting comments here, is there any other deployment tool being used that users would like support for?

**Comment by mnaser** [comment]
@ngyenhuukhoi is there any other distro that you use which would make sense to keep this ticket open?

**Comment by ngyenhuukhoi** [comment]
Hello.
What you mean?

**Comment by mnaser** [comment]
We have tasks to integrate this driver with both Kolla and OSA, do you know of any other OpenStack distribution that we should cover in integrations?

**Comment by ngyenhuukhoi** [comment]
Hello,
I know only Kolla and OSA which r the most famous tool.
Thank you for response,

**Comment by mnaser** [comment]
closing in favour of https://github.com/vexxhost/magnum-cluster-api/issues/151 and https://github.com/vexxhost/magnum-cluster-api/issues/152
