### ISSUE TITLE
Cluster status is not updated properly

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/magnum-cluster-api#57]
I've been noticing that on every action took on a magnum cluster, it delays up to 1 minute to have it reflected on magnum api. 

In some cases, like a sequence of rolling upgrades, the second time we upgrade a cluster ( with UPDATE_COMPLETE status ), it keeps doing the upgrade, but it doesnt update the magnum status to UPDATE_IN_PROGESS. 

This might confuse the end-user on what is the operation being done at the moment.

**Comment by okozachenko1203** [comment]
- [ ] Cluster status is not changed from `UPDATE_COMPLETE` to `UPDATE_IN_PROGRESS` (the case which @guilhermesteinmuller mentioned above)
- [ ] Cluster status is not reflecting the failed result. Even though cluster creation failed because of resource lack, it keeps `CREATE_IN_PROGRESS` status.

**Comment by mnaser** [comment]
@okozachenko1203 so I think this issue should track the first part of your message, and the second part is covered in #64

**Comment by okozachenko1203** [comment]
Cluster status transition from `COMPLETE` to `IN_PROGRESS` is done by conductor's periodic service `ClusterUpdateJob`. mcapi driver only does update the status from `IN_PROGRESS` to `COMPLETE`.
This is more likely related to the race condition and the conductor was stuck to do the periodic service, and not related to mcapi.

**Comment by mnaser** [comment]
i think this issue still valid, if I start an upgrade o fthe cluster, it goes into COMPLETE right away because the reconciler did not start the upgrade yet.. we should somehow find a way to 'delay' the check or know that it will go into reconciliation
