### ISSUE TITLE
Integrate to Kolla Ansible

### ISSUE THREAD

**Issue by ngyenhuukhoi** [vexxhost/magnum-cluster-api#65]
Hello.
I want to test this project with multi node deployment. Can we have some guideline for it?
Thanks

**Comment by okozachenko1203** [comment]
@ngyenhuukhoi I updated https://github.com/vexxhost/magnum-cluster-api/issues/56#issuecomment-1377579405
Only the 3rd step `install magnum-cluster-api driver on your cloud` depends on your cloud deployment method. Other steps should be same.

**Comment by ngyenhuukhoi** [comment]
Thank you for replying. :)
Nguyen Huu Khoi
