### ISSUE TITLE
Integration with Keystone auth

### ISSUE THREAD

**Issue by heytrav** [vexxhost/magnum-cluster-api#66]
When following the instructions in #56 my cluster create fails with an error resembling the following:

```
{
  "status": "CREATE_FAILED",
  .
  .
  "status_reason": "(https://10.10.4.4:35357/v3/users/590bc654b1014a2fa568631ba399524a/application_credentials): The resource could not be found. (HTTP 404) (Request-ID: req-6204ca58-87f5-4868-bc2c-ba4159399fba)",
  .
  .
}
```

My question: Is there a way around using application credentials to authenticate? We are using a bit older version of Keystone (Pike) and are probably not going to be able to upgrade very soon.

**Comment by okozachenko1203** [comment]
@heytrav current version only supports application credential to auth cluster-api against openstack.

**Comment by okozachenko1203** [comment]
@mnaser Do we have any plan of supporting user/pwd auth method for old versions?

We need to indicate the compatible min openstack version in the doc at least for now (for app credential api, keystone>=13.0.0 Queens)

**Comment by mnaser** [comment]
@heytrav: I'm not sure about how we can support this without application credentials.  we'd have to switch to using trusts instead, I'm not a fan of them...

since application credentials have been around for quite sometime, I think adding support for trusts would be more of a "contributions welcome" sort of change.

**Comment by heytrav** [comment]
@mnaser @okozachenko1203 Thank you both for your input. We're looking to move to ClusterAPI so we'll explore ways we can integrate additional auth methods.
